In [82]:
import numpy as np

In [58]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [78]:
a.shape

(3, 3)

In [49]:
a.ndim

2

In [79]:
a.size

9

---

In [124]:
sq = np.array([[4, 9, 16, 25, 36]])
np.sqrt(sq)

array([[2., 3., 4., 5., 6.]])

In [119]:
sin = np.array([[1, 2, 3, 4, 5]])
np.sin(sin)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427]])

In [97]:
cos = np.array([[1, 2, 3, 4, 5]])
np.cos(cos)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219]])

In [98]:
tan = np.array([[1, 2, 3, 4, 5]])
np.tan(tan)

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501]])

---

In [127]:
zero = np.array([[0, 1, 2], [3, 4, 5]])
np.zeros(zero.shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [130]:
one = np.array([[0, 1, 2], [3, 4, 5]])
np.ones(one.shape)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [135]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

In [74]:
re = np.array([[0, 1, 2], [3, 4, 5]])

In [75]:
np.reshape(re, (3, -1))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [76]:
re.reshape((3, 2))

array([[0, 1],
       [2, 3],
       [4, 5]])

---

In [138]:
trans = np.array([[0, 1, 2], [3, 4, 5]])
trans.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [150]:
np.random.rand(10)

array([0.41004371, 0.91811612, 0.00207011, 0.59976347, 0.63789971,
       0.61340129, 0.87340208, 0.71286851, 0.78616908, 0.1695464 ])

In [143]:
np.random.randn(10)

array([-0.35474985, -0.65075913, -1.18868158,  2.49054771, -0.98557701,
       -0.3647411 ,  0.79287963, -2.10699111,  0.74246506, -0.37143223])

In [189]:
np.random.choice(11, (5, 5))

array([[ 9,  0,  9, 10,  4],
       [10,  7,  9,  7,  4],
       [ 9,  2,  1,  9,  2],
       [ 2,  9,  6,  2,  3],
       [ 2,  4,  3,  8,  9]])

In [211]:
x = np.random.rand(100).reshape((25, 4))
w = np.random.rand(4).reshape((4, 1))
np.matmul(x, w)

array([[0.6449001 ],
       [0.99408303],
       [0.96405953],
       [0.69654436],
       [0.58150398],
       [0.28720983],
       [0.69909046],
       [0.42956958],
       [0.93871271],
       [0.9800108 ],
       [0.6254399 ],
       [0.52119103],
       [0.6898989 ],
       [0.86724435],
       [0.59989556],
       [0.37699432],
       [0.30600389],
       [0.8138587 ],
       [0.68190398],
       [0.73888991],
       [0.48896222],
       [0.4016816 ],
       [0.22528171],
       [1.10922737],
       [0.9996311 ]])

In [212]:
x_ = np.random.rand(100).reshape((25, 4))
w_ = np.random.rand(4).reshape((4, 1))
np.dot(x_, w_)

array([[0.67915413],
       [0.20920437],
       [0.59246331],
       [1.16759548],
       [0.36421287],
       [0.79071213],
       [0.93781223],
       [0.52232919],
       [1.05894393],
       [0.99955061],
       [0.53736207],
       [0.45980341],
       [0.38131211],
       [1.24101434],
       [1.12468511],
       [0.79666945],
       [1.0139016 ],
       [1.37849185],
       [0.64201136],
       [0.7696302 ],
       [0.69805316],
       [0.6775801 ],
       [0.75776226],
       [0.93272334],
       [1.24549546]])